### ISSUE TITLE
[vite] Internal server error: DEFINED_RULES.includes is not a function

### ISSUE THREAD

**Issue by christoph-kluge** [axe-api/validator#68]
I've tried the `isRegistered`-function which was introduced in #60 but it seems like something is not to working.

```diff
- if (!('uuid' in DEFINED_RULES)) {
+ if (!isRegistered('uuid')) {
    register(
        "uuid", // The rule name
        (value: any) => validateUuid(value), // The rule functions
        // Translations
        {},
    );
}
```

is causing

```
[vite] Internal server error: DEFINED_RULES.includes is not a function
      at isRegistered (file:///project/node_modules/robust-validator/dist/index.mjs:421:26)
      at eval (/project/app/services/validator.server.ts:9:44)
      at ESModulesEvaluator.runInlinedModule (file:///project/node_modules/vite/dist/node/module-runner.js:1049:5)
      at SSRCompatModuleRunner.directRequest (file:///project/node_modules/vite/dist/node/module-runner.js:1271:61)
```

Do you have any suggestions?

### Environment

SSR rendered appliation

```
% node --version
v23.7.0
```

```
% npm list | grep vite
├── vite-tsconfig-paths@5.1.4
├── vite@6.0.11
```

**Comment by ozziest** [comment]
@christoph-kluge , thanks for the feedback. 🤗  

Definitely, it's a bug. I'll fix it today.
